-- Create database
CREATE DATABASE divvy;

-- Use database
USE divvy;

-- Create table
CREATE TABLE rides (
  ride_id varchar(25) PRIMARY KEY,
  rideable_type VARCHAR(25),
  started_at DATETIME,
  ended_at DATETIME,
  start_station_name VARCHAR(255),
  start_station_id VARCHAR(50),
  end_station_name VARCHAR(255),
  end_station_id VARCHAR(50),
  start_lat DECIMAL(10, 8),
  start_lng DECIMAL(11, 8),
  end_lat DECIMAL(10, 8),
  end_lng DECIMAL(11, 8),
  member_casual VARCHAR(10),
  started_at_time DATETIME,
  ended_at_time DATETIME,
  duration_time TIME
);

-- Load files into table
LOAD DATA INFILE 'cleaned_csv1.csv' 
INTO TABLE rides
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'cleaned_csv2.csv' 
INTO TABLE rides
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'cleaned_csv3.csv' 
INTO TABLE rides
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'cleaned_csv4.csv' 
INTO TABLE rides
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'cleaned_csv5.csv' 
INTO TABLE rides
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'cleaned_csv6.csv' 
INTO TABLE rides
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'cleaned_csv7.csv' 
INTO TABLE rides
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'cleaned_csv8.csv' 
INTO TABLE rides
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'cleaned_csv9.csv' 
INTO TABLE rides
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'cleaned_csv10.csv' 
INTO TABLE rides
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'cleaned_csv11.csv' 
INTO TABLE rides
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'cleaned_csv12.csv' 
INTO TABLE rides
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'cleaned_csv13.csv' 
INTO TABLE rides
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'cleaned_csv14.csv' 
INTO TABLE rides
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES;


